name: Upload to A Repository

on:
  push:
    branches:
      - main  # 可以根据需要调整触发条件

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout B Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # 设置你的 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # 根据你的项目设置调整命令

      - name: Checkout A Repository
        uses: actions/checkout@v2
        with:
          repository: username/a-repo  # 替换为 A 仓库的用户名和仓库名称
          path: a-repo  # 将 A 仓库检出到指定路径
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用自动提供的令牌

      - name: Copy build files
        run: |
          cp -r ./dist/* ./a-repo/  # 根据你的打包输出路径调整

      - name: Commit and push changes
        working-directory: ./a-repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update build files from B repository" || echo "No changes to commit"
          git push
